default:
	flutter clean
	flutter pub get
	flutter run

create:
	flutter pub get
	dart run flutter_launcher_icons:main
	flutter clean
	flutter pub get
	flutter build apk
	flutter install


emulator:
	flutter emulators --launch pixel_brokeaf


